### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by WXYyuyu** [nghuyong/cscd-ime#1]
你好，我在执行构建伪数据的fetch_google_input_method_result()方法时，一直出现如下错误：

HTTPSConnectionPool(host='inputtools.google.com', port=443): Max retries exceeded with url: /request?text=%7C%E4%B8%80%2Cbu&itc=zh-t-i0-pinyin&num=11&cp=0&cs=1&ie=utf-8&oe=utf-8&app=demopage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FE28328DA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

请问有什么方法可以成功连接使用谷歌输入法？

**Comment by nghuyong** [comment]
需要能正常访问Google（能翻墙）才可使用Google输入法

**Comment by WXYyuyu** [comment]
感谢您的回复。但具体怎么翻墙，代码中的url路径是否需要改动，能否提供些帮助

**Comment by nghuyong** [comment]
如何访问Google需要您自己解决。
可以访问Google后，代码不用调整。

**Comment by WXYyuyu** [comment]
我可以成功访问Google，并且扩展里装了谷歌Google输入工具，但依旧报上面的错误。想问一下您使用的request和urllibs的版本是多少？还有没有其他原因导致报错？

**Comment by nghuyong** [comment]
你测试一下你在命令行能不能访问Google，我这里测试是ok的
requests == 2.28.1
